### ISSUE TITLE
ping360: make range scale more dynamic and user-friendly

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#600] opened 2019-07-25 20:25 UTC
It will be nice if the range scale on ping360 behaved the same as the depth scale on ping1d.

The ping1d adjusts **both** the number of increments _and_ the increment value to make the scale easy for humans to interpolate between tick marks.: https://github.com/bluerobotics/ping-viewer/blob/master/qml/DepthAxis.qml#L16

For example, when the range is 30, the labels are 7.5, 15, 22.5, 30:
![Screenshot_20190725_162344](https://user-images.githubusercontent.com/8315108/61906134-a717fb80-aef8-11e9-97cb-20638abd03e1.png)

I think it would be more natural and easy to interpret the data if the labels were [5, 10, 15, 20, 25, 30], or [10, 20, 30].

**Comment by jaxxzer** [comment] 2019-07-25 20:32
https://giphy.com/gifs/S9o3EXFHwpG0xrzOsU

**Comment by patrickelectric** [comment] 2019-10-11 10:32
Duplicate of #586

**Closed by patrickelectric** 2019-10-11 10:32 UTC
Labels: enhance, nice-to-have
