### ISSUE TITLE
Add option to disable automatic port scan/device detection

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#763] opened 2019-09-20 18:52 UTC
This can interfere with other things, like a pixhawk or other serial device connected to the computer.

**Comment by patrickelectric** [comment] 2019-09-23 15:01
It should not  interfere with other hardwares, what is the problem with that ?

**Comment by patrickelectric** [comment] 2019-11-15 11:47
Duplicate of #476

**Closed by patrickelectric** 2019-11-15 11:47 UTC
Labels: needs-confirmation, question
